name: Exploring variables & secrets
on: push
env:
  USERNAME: Boris
  PASSWORD: p4ssw0rd
  ANNEE: 2025 
jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
      - name: Print Variables
        run: echo $USERNAME ${{ env.PASSWORD }}

      - name: Print Pythoin version
        run:  python --version

  deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
      - name: Print Variables
        run: echo $ANNEE