name: Generate ASCII Artwork
on: push
jobs:
  build_job:
      runs-on: ubuntu-latest
      steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run:  cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

      - name: Sleep for 30 sec
        uses: sleep 30

  test_job:
      runs-on: ubuntu-latest
      steps:
      - name: Sleep for 10 sec
        run: sleep 10

      - name: Test if file exists
        run: grep -i "dragon" dragon.txt

  deploy_job:
      runs-on: ubuntu-latest
      steps:
      - name: Read File
        run: cat dragon.txt

      - name: Deploy
        run: echo Deploying now!