    name: Use Artifact Workflow
    on: push
    jobs:
      build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run:  cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

        - name: Upload artifact file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-artifact
            path: dragon.txt

      test_job:
          needs: build_job
          runs-on: ubuntu-latest
          steps:
          - name: Download artifact file
            uses: actions/download-artifact@v4
            with:
              name: dragon-artifact

          - name: Test if file exists
            run: grep -i "dragon" dragon.txt

      deploy_job:
            needs: [build_job, test_job]
            runs-on: ubuntu-latest
            steps:
            - name: Download artifact file
              uses: actions/download-artifact@v4
              with:
                name: dragon-artifact

            - name: Read File
              run: cat dragon.txt

            - name: Deploy
              run: echo Deploying now!